#ESTE FRAGMENTO FUE GENERADO AUTOMATICAMENTE POR LA CONSOLA
#backend:
#    resource: "@BackendBundle/Resources/config/routing.yml"
#    prefix:   /

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /
